// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function RejectBattleChallengeFromUser(arg1:string):void;

export function SDLogout():void;

export function SendBattleChallengeToUser(arg1:string,arg2:string,arg3:string):void;

export function CancelBattleChallengeToUser(arg1:string):void;

export function CancelSearchForBattle():void;

export function MakeBattleChoice(arg1:Array<main.BattleChoice>):void;

export function SearchForBattle(arg1:string,arg2:string):void;

export function SendPM(arg1:string,arg2:string):void;

export function AcceptBattleChallengeFromUser(arg1:string,arg2:string):void;

export function GetFormats():Promise<main.FormatInfo>;

export function SDLogin(arg1:string,arg2:string):void;
