// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RejectBattleChallengeFromUser(arg1) {
  window['go']['main']['App']['RejectBattleChallengeFromUser'](arg1);
}

export function SDLogout() {
  window['go']['main']['App']['SDLogout']();
}

export function SendBattleChallengeToUser(arg1, arg2, arg3) {
  window['go']['main']['App']['SendBattleChallengeToUser'](arg1, arg2, arg3);
}

export function CancelBattleChallengeToUser(arg1) {
  window['go']['main']['App']['CancelBattleChallengeToUser'](arg1);
}

export function CancelSearchForBattle() {
  window['go']['main']['App']['CancelSearchForBattle']();
}

export function MakeBattleChoice(arg1) {
  window['go']['main']['App']['MakeBattleChoice'](arg1);
}

export function SearchForBattle(arg1, arg2) {
  window['go']['main']['App']['SearchForBattle'](arg1, arg2);
}

export function SendPM(arg1, arg2) {
  window['go']['main']['App']['SendPM'](arg1, arg2);
}

export function AcceptBattleChallengeFromUser(arg1, arg2) {
  window['go']['main']['App']['AcceptBattleChallengeFromUser'](arg1, arg2);
}

export function GetFormats() {
  return window['go']['main']['App']['GetFormats']();
}

export function SDLogin(arg1, arg2) {
  window['go']['main']['App']['SDLogin'](arg1, arg2);
}
